export enum ActionType {
    GET_TOP_RATED_MOVIES = 'GET_TOP_RATED_MOVIES',
    GET_POPULAR_MOVIES = 'GET_POPULAR_MOVIES',
    GET_NOW_PLAYING_MOVIES = 'GET_NOW_PLAYING_MOVIES',
    GET_UPCOMING_MOVIES = 'GET_UPCOMING_MOVIES',

    GET_TOP_RATED_TVSHOWS = 'GET_TOP_RATED_TVSHOWS',
    GET_POPULAR_TVSHOWS = 'GET_POPULAR_TVSHOWS',
    GET_ON_THE_AIR_TV_SHOWS = 'GET_ON_THE_AIR_TV_SHOWS',

    GET_POPULAR_PEOPLE = 'GET_POPULAR_PEOPLE'
}